---
name: Main CI

on:
  push:
    tags: [ 'v.*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set Version
        id: set-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        env:
          APP_NAME: graylog
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,scope=${{ github.workflow }}
          cache-from: type=gha,scope=${{ github.workflow }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:latest
            # ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ steps.set-version.outputs.version }}
          build-args: |
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}